services:
  authlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authlab-app
    ports:
      - "8080:8080"
    depends_on:
      - authlab-db

  authlab-db:
    image: postgres:16
    container_name: authlab-postgres
    environment:
      POSTGRES_DB: authlab
      POSTGRES_USER: authlab
      POSTGRES_PASSWORD: authlab123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: